name: "Lint, Build and Test on Pull Request"

on:
  pull_request:

jobs:
  call-lint-build-test:
    uses: ./.github/workflows/reusable-lint-build-test.yml
    secrets: inherit
    with:
      upload_artifacts: false
