name: "Lint, Build and Test on Push (Non-Main Branches)"

on:
  push:
    branches-ignore:
      - main

jobs:
  call-lint-build-test:
    uses: ./.github/workflows/reusable-lint-build-test.yml
    secrets: inherit
    with:
      upload_artifacts: false
