name: "Release on PR from Main"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  call-lint-build:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/reusable-lint-build-test.yml
    secrets: inherit
    with:
      upload_artifacts: true

  create-tag-and-release:
    needs: call-lint-build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating tags & releases

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full commit history for versioning

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts  # Matches the artifact name from the reusable workflow
          path: dist

      - name: Extract project version from pyproject.toml
        run: echo "VERSION=v$(grep -oP '(?<=version = ")[^"]+' pyproject.toml)" >> $GITHUB_ENV

      - name: Get latest tag version
        run: echo "LATEST_TAG_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Generate commit log
        if: env.VERSION != env.LATEST_TAG_VERSION
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"

          # Fetch the latest commits
          if git rev-parse "$LATEST_TAG_VERSION" >/dev/null 2>&1; then
            LOG=$(git log "$LATEST_TAG_VERSION"..HEAD --pretty=format:"| [\`%h\`]($REPO_URL/commit/%H) | %s |" --reverse)
          else
            LOG=$(git log --pretty=format:"| [\`%h\`]($REPO_URL/commit/%H) | %s |" --reverse)
          fi

          printf "CHANGELOG<<EOF\n| Commit ID | Commit Message |\n|-----------|---------------|\n%s\nEOF\n" "$LOG" >> "$GITHUB_ENV"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: env.VERSION != env.LATEST_TAG_VERSION
        with:
          tag_name: ${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
          generate_release_notes: true
          files: |
            dist/*.whl
            dist/*.tar.gz
